# Generated by Django 5.2.8 on 2026-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('device', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('battery', models.PositiveSmallIntegerField()),
                ('color', models.CharField(default='#000000', max_length=32)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=32)),
                ('change', models.CharField(max_length=16)),
                ('up', models.BooleanField(default=True)),
                ('color', models.CharField(default='#000000', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=32)),
                ('pct', models.PositiveSmallIntegerField()),
                ('color', models.CharField(default='#000000', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
