# Generated by Django 5.2.8 on 2026-04-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(default='Main Entrance', max_length=128)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Warning', 'Warning')], default='Online', max_length=16)),
                ('battery', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('faPumpSoap', 'Soap Dispenser'), ('faDroplet', 'Water Valve'), ('faTemperatureHalf', 'Temperature Sensor'), ('faHandsWash', 'Handwash Counter'), ('faVolumeHigh', 'Speaker System'), ('faLightbulb', 'Visual Indicator'), ('faBolt', 'Power Device'), ('faServer', 'Server')], default='faServer', max_length=64)),
                ('color', models.CharField(default='#6366f1', max_length=16)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('wired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('soap_level', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
