# Generated by Django 5.2.8 on 2026-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.CharField(choices=[('faPumpSoap', 'Soap Dispenser'), ('faDroplet', 'Water Valve'), ('faTemperatureHalf', 'Temperature Sensor'), ('faHandsWash', 'Handwash Counter'), ('faVolumeHigh', 'Speaker System'), ('faLightbulb', 'Visual Indicator'), ('faBolt', 'Power Device'), ('faServer', 'Server'), ('faEye', 'IR Proximity Sensor'), ('faWater', 'Ultrasonic Sensor'), ('faToggleOn', 'Relay Module'), ('faDisplay', 'Display Module'), ('faMusic', 'MP3 Player Module')], default='faServer', max_length=64),
        ),
    ]
