# Generated by Django 5.2.8 on 2026-04-05 17:55

import random
from django.db import migrations, models


def random_device_color():
    colors = ['#6366f1', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4', '#84cc16', '#f97316', '#ec4899', '#14b8a6']
    return random.choice(colors)


def update_default_colors(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.filter(color='#6366f1'):
        device.color = random_device_color()
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.CharField(default=random_device_color, max_length=16),
        ),
        migrations.RunPython(update_default_colors),
    ]
