# Generated by Django 5.2.8 on 2026-04-11 13:51

import apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.CharField(default=apps.devices.models.random_device_color, max_length=16),
        ),
    ]
