# Generated by Django 5.2.8 on 2026-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(choices=[('devices', 'Devices'), ('sensors', 'Sensors'), ('boards', 'Boards'), ('other', 'Other')], max_length=16)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_endpoint', models.URLField(default='http://localhost:8000')),
                ('api_key', models.CharField(blank=True, max_length=256)),
                ('poll_interval', models.PositiveIntegerField(default=30)),
                ('default_location', models.CharField(default='Main Entrance', max_length=128)),
                ('device_timeout', models.PositiveIntegerField(default=60)),
                ('temperature_unit', models.CharField(default='Celsius', max_length=16)),
                ('auto_reconnect', models.BooleanField(default=True)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('low_threshold', models.PositiveSmallIntegerField(default=20)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('push_alerts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
