# Generated by Django 5.2.8 on 2026-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('device', models.CharField(default='IoT-Station-01', max_length=128)),
                ('soap_usage', models.FloatField(default=0.0)),
                ('water_usage', models.FloatField(default=0.0)),
                ('handwashes', models.PositiveIntegerField(default=0)),
                ('unwashed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'device')},
            },
        ),
    ]
